changed makefile

diff --git a/PA2/makefile b/PA2/makefile
--- a/PA2/makefile
+++ b/PA2/makefile
@@ -1,17 +1,28 @@
+SERVER_DIR = server
+BUILD_DIR = $(SERVER_DIR)/build
+SERVER_BIN = $(BUILD_DIR)/server
 
-all: server run
 
-server:
-	-cd server && $(MAKE)
-	
+all: $(SERVER_BIN) run
+
+$(SERVER_BIN): 
+	@echo "Building server in $(SERVER_DIR)..."
+	cd $(SERVER_DIR) && $(MAKE)
+	@test -f $(SERVER_BIN) || (echo "Server binary not found!"; exit 1)
+
+# Clean build files
 .PHONY: clean
 clean:
-	-cd server && $(MAKE) clean
+	@echo "Cleaning..."
+	cd $(SERVER_DIR) && $(MAKE) clean
 
+# Run tests
 .PHONY: test
 test:
-	-cd server && python3 stress.py
+	cd $(SERVER_DIR) && python3 stress.py
 
+# Run server
 .PHONY: run
-run: 
-	-cd server && ./build/server 8000
+run: server
+	cd $(SERVER_DIR) && $(SERVER_BIN) 8000; \
+	
